<?php
    session_start();
    unset($_SESSION["ID"]);
    unset($_SESSION["name"]);
    unset($_SESSION["username"]);
    unset($_SESSION["bookpermission"]);
    unset($_SESSION["categoriespermission"]);
    unset($_SESSION["userspermission"]);
    header("Location:login.php");
?>